# Initially coming from 
# https://github.com/VioletGiraffe/qmake-project-template/blob/master/.github/workflows/CI.yml
# Used according to Apache-2.0 license

name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches: 
      - master 
      - Development 
  pull_request:
    branches:
      - master 
      - Development

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: Build on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Linux - Update gcc and g++
      if: startsWith(matrix.os, 'ubuntu')
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        sudo apt update -y; sudo apt install -qq gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 50
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 50
        g++ --version
        sudo apt install libgl1-mesa-dev doxygen
        sudo apt install qt6-base-dev

    - name: Windows - Install Qt
      if: startsWith(matrix.os, 'windows')
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.2.*

    - name: Windows - Install Doxygen
      if: startsWith(matrix.os, 'windows')
      uses: ssciwr/doxygen-install@v1

    - name: Common - Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Common - Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


    - name: Windows - Run Doxygen
      if: startsWith(matrix.os, 'windows')
      run: doxygen Doxyfile
 
    - name: Linux - Run Doxygen
      if: startsWith(matrix.os, 'ubuntu')
      run: doxygen Doxyfile
 
    - name: Windows - Deployment Package
      if: startsWith(matrix.os, 'windows')
      run: |
        mkdir ${{github.workspace}}\release\all\
        cp -R ${{github.workspace}}/docs ${{github.workspace}}\release\all\
        cp ${{github.workspace}}/build/gui/Release/FractalsDiscovery.exe ${{github.workspace}}\release\all\
        cd ${{github.workspace}}\release\all\
        windeployqt.exe FractalsDiscovery.exe --release
        ls
        Compress-Archive -Path ${{github.workspace}}\release\all\ -DestinationPath ${{github.workspace}}\release\FractalsDiscovery.zip

    - name: Linux - Deployment Package
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        mkdir -p ${{github.workspace}}/release/all/
        cp -r ${{github.workspace}}/docs ${{github.workspace}}/release/all/
        cp ${{github.workspace}}/build/gui/FractalsDiscovery ${{github.workspace}}/release/all/
        cp /usr/lib64/libQt6Widgets.so ${{github.workspace}}/release/all/
        cp /usr/lib64/libQt6Gui.so ${{github.workspace}}/release/all/
        cp /usr/lib64/libQt6Core.so ${{github.workspace}}/release/all/
        cd ${{github.workspace}}/release/all/
        ldd FractalsDiscovery
        tar cvzf ${{github.workspace}}/release/FractalsDiscovery.tar.gz .
 
    - name: Windows - Upload Production-Ready Files
      if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v4
      with:
         name: WindowsPackage
         path: ${{github.workspace}}/release/FractalsDiscovery.zip

    - name: Linux - Upload Production-Ready Files
      if: startsWith(matrix.os, 'ubuntu')
      uses: actions/upload-artifact@v4
      with:
         name: UbuntuPackage
         path: ${{github.workspace}}/release/FractalsDiscovery.tar.gz

